baseURL = 'https://example.org/'
languageCode = 'en'
title = 'Mi portafolio de practicas'
theme = "wowchemy"
[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Pr√°cticas"
    url = "/practica2/"
    weight = 2
